language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t medrahim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true medrahim/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-527654417117"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: "$AWS_SECRET_KEY"